image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

stages:
  - test

terraform_format:
  stage: test
  script:
    - tf=$(terraform fmt -write=false -diff); if [[ -n "$tf" ]]; then printf "$tf\n\n\nSome terraform files failed syntax validation, run 'terraform fmt' to fix\n\n"; exit 1; fi

ansible_lint:
  stage: test
  image: python:3.7.4
  variables:
    PIP_CACHE_DIR: "pip-cache"
  cache:
    paths:
      - pip-cache
  script:
    - pip3 install ansible-lint
    - ansible-lint -x 301 -x 305 -x 701  ansible/playbook.yaml

shellcheck:
  stage: test
  image: koalaman/shellcheck-alpine
  script:
    - shellcheck templates/user_data.tmpl
