---
- name: Update and upgrade apt packages
  apt:
    update_cache: yes
    upgrade: "yes"

- name: Install package "python3-boto"
  apt:
    name: "python3-boto=2.44.0-1ubuntu2.18.04.0"

- name: Install package "python-boto"
  apt:
    name: "python-boto=2.44.0-1ubuntu2.18.04.0"

- name: Set the hostname
  hostname:
    name: "bastion-{{ networking_environment }}"

- name: Find EC2 Instance ID
  uri:
    url: http://169.254.169.254/latest/meta-data/instance-id
    return_content: yes
  register: instance_id

- name: Associate instance with Elastic IP
  ec2_eip:
    device_id: "{{ instance_id.content }}"
    ip: "{{ bastion_ip }}"
    allow_reassociation: yes
