---
- name: Update and upgrade apt packages
  apt:
    update_cache: yes
    upgrade: "yes"

- name: Install package "python3-botocore"
  apt:
    name: "python3-botocore=1.8.48+repack-1"
  become: yes

- name: Install package "python3-boto3"
  apt:
    name: "python3-boto3=1.4.2-1"
  become: yes

- name: Install package "python-botocore"
  apt:
    name: "python-botocore=1.8.48+repack-1"
  become: yes

- name: Install package "python-boto3"
  apt:
    name: "python-boto3=1.4.2-1"
  become: yes

- name: Set the hostname
  hostname:
    name: "bastion-{{ networking_environment }}"

- name: Find EC2 Instance ID
  uri:
    url: http://169.254.169.254/latest/meta-data/instance-id
    return_content: yes
  register: instance_id

- name: Associate instance with Elastic IP
  ec2_eip:
    device_id: "{{ instance_id.content }}"
    ip: "{{ bastion_ip }}"
    allow_reassociation: yes
